In [1]:
import numpy as np
from scipy.ndimage import geometric_transform

In [2]:
a = np.arange(12.).reshape((4, 3))

In [3]:
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [4]:
def shift_func(output_coords):
    return (output_coords[0] - 0.5, output_coords[1] - 0.5)

In [5]:
geometric_transform(a, shift_func)

array([[0.    , 0.    , 0.    ],
       [0.    , 1.3625, 2.7375],
       [0.    , 4.8125, 6.1875],
       [0.    , 8.2625, 9.6375]])

In [6]:
b = [1, 2, 3, 4, 5]

In [7]:
def shift_func(output_coords):
    return (output_coords[0] - 3,)

In [8]:
geometric_transform(b, shift_func, mode='constant')

array([0, 0, 0, 1, 2])

In [9]:
geometric_transform(b, shift_func, mode='nearest')

array([1, 1, 1, 1, 2])

In [10]:
geometric_transform(b, shift_func, mode='reflect')

array([3, 2, 1, 1, 2])

In [11]:
geometric_transform(b, shift_func, mode='wrap')

array([2, 3, 4, 1, 2])